pipeline {
	agent any

	environment {
		DOCKER_IMAGE = "hajarhaoud/spring-app"
		DOCKER_HUB_CREDS = 'docker-hub-credentials'
	}

	stages {
		stage('Checkout Code') {
			steps {
				git branch: 'main', url: 'https://github.com/HajarHaoud/pipeline-spring.git'
			}
		}

		stage('Build Artifact') {
			steps {
				sh 'mvn clean package -DskipTests'
			}
		}

		stage('Build & Push Docker Image') {
			steps {
				script {
					docker.withRegistry('', DOCKER_HUB_CREDS) {
						def customImage = docker.build("${DOCKER_IMAGE}:${env.BUILD_ID}")
						customImage.push()
						customImage.push('latest')
					}
				}
			}
		}

		stage('Deploy to K8s') {
			steps {
				withCredentials([file(credentialsId: 'k8s-config', variable: 'KUBECONFIG')]) {
					sh "kubectl --kubeconfig=${KUBECONFIG} apply -f deployment.yaml"
					sh "kubectl --kubeconfig=${KUBECONFIG} rollout restart deployment/spring-app"
				}
			}
		}
	}
}