pipeline {
	agent any

	tools {
		maven 'maven3'
	}

	environment {
		DOCKER_USER = 'hajarhaoud'
		IMAGE_NAME = 'spring-app'
		IMAGE_TAG = "${env.BUILD_NUMBER}"
	}

	stages {

		sstage('1. Checkout') {
			steps {
				git branch: 'main', url: 'https://github.com/HajarHaoud/pipeline-spring.git'
			}
		}

		stage('2. Vérification Structure') {
			steps {
				sh '''
                    echo "=== Structure du workspace ==="
                    pwd
                    ls -la
                    echo "=== Contenu de spring-pipeline/ ==="
                    ls -la spring-pipeline/
                '''
			}
		}

		stage('3. Build Maven') {
			steps {
				dir('spring-pipeline') {  // ← C'est ici qu'il faut aller !
					sh 'mvn clean package -DskipTests'
				}
			}
		}

		stage('5. Build Docker') {
			steps {
				dir('spring-pipeline') {  // ← Pareil pour Docker
					withCredentials([usernamePassword(credentialsId: 'docker-hub-creds', passwordVariable: 'PASS', usernameVariable: 'USER')]) {
						sh 'docker build -t hajarhaoud/spring-app:latest .'
						sh "echo $PASS | docker login -u $USER --password-stdin"
						sh 'docker push hajarhaoud/spring-app:latest'
					}
				}
			}
		}


		stage('4. Deploy to K8s') {
			steps {
				// Si ton fichier deployment.yaml est AUSSI dans spring-pipeline
				dir('spring-pipeline') {
					withCredentials([file(credentialsId: 'k8s-config', variable: 'KUBECONFIG')]) {
						sh "kubectl --kubeconfig=${KUBECONFIG} apply -f deployment.yaml"
						sh "kubectl --kubeconfig=${KUBECONFIG} rollout restart deployment/spring-app"
					}
				}
			}
		}
	}
}