pipeline {
	agent any

	stages {
		stage('Checkout Code') {
			steps {
				git 'https://github.com/HajarHaoud/pipeline-CI-CD.git'
			}
		}

		stage('Build & Test') {
			steps {
				dir('spring-pipeline'){
					sh 'chmod +x mvnw'
					// On utilise Docker pour builder afin d'éviter d'installer Maven sur Jenkins
					sh './mvnw clean package -DskipTests'
				}
			}
		}

		stage('Vérification JAR') {
			steps {
				dir('spring-pipeline') {
					// On vérifie que le fichier .jar a bien été créé
					sh 'ls -l target/'
					echo "BRAVO ! Le build Maven est réussi."
				}
			}
		}

		stage('Build Docker Image') {
			steps {
				sh 'docker build -t mon-app-spring .'
			}
		}

		stage('Run Application') {
			steps {
				// On arrête l'ancien conteneur s'il existe et on lance le nouveau
				sh '''
                docker stop mon-app-container || true
                docker rm mon-app-container || true
                docker run -d -p 8081:8080 --name mon-app-container mon-app-spring
                '''
			}
		}
	}
}